version: '3'
services:
  web:
    env_file: .env
    image: node
    ports:
      - "$PORT:$PORT"
    volumes:
      - .:/app
    working_dir: /app
    command: ./entrypoint.sh
    depends_on:
      - db

  db:
    image: mongo:4.4
    ports:
      - "27017:27017"